"""Sixth  Migration

Revision ID: 93bb02e869e1
Revises: 32fb6f080dc0
Create Date: 2018-09-14 17:19:36.976228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bb02e869e1'
down_revision = '32fb6f080dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_blogpost_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['blogpost_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blogpost_id_fkey', 'comments', 'blogposts', ['blogpost_id'], ['id'])
    # ### end Alembic commands ###
