"""Sixth  Migration bugs fixes

Revision ID: a4f30a60b61c
Revises: 93bb02e869e1
Create Date: 2018-09-14 17:27:23.413175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f30a60b61c'
down_revision = '93bb02e869e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_blogpost_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'blogposts', ['blog_id'], ['id'])
    op.drop_column('comments', 'blogpost_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogpost_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blogpost_id_fkey', 'comments', 'users', ['blogpost_id'], ['id'])
    op.drop_column('comments', 'blog_id')
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
