"""Seventh  Migration

Revision ID: a9b41dbc7fa4
Revises: a4f30a60b61c
Create Date: 2018-09-15 03:55:49.538432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b41dbc7fa4'
down_revision = 'a4f30a60b61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'image')
    # ### end Alembic commands ###
